### ISSUE TITLE
enabling virtualization / wsl2 is only for windows 

### ISSUE THREAD

**Issue by katherineleyq** [UCSB-MEDS/UCSB-MEDS.github.io#19]
i don't think those with macs will encounter this problem so i'd suggest deleting the extra steps for docker installation in the mac portion because it might be confusing

**Comment by katherineleyq** [comment]
also this is small, but it says "you made need to go through the following steps to install Docker on a PC." instead of "you may..."

**Comment by allisonhorst** [comment]
Thanks for looking through this Kat! For the MacOS section on my end the Docker install just contains "Visit docker.com/get-started and install Docker Desktop for your operating system. Note: If you have a Mac, you must select either the Intel Chip or the more recent computers will have the Apple chip. Once installed, drag & drop into Applications" -- possible you had scrolled into the Windows section?

**Comment by katherineleyq** [comment]
oops you are def right. i thought they were side by side so i read it wrong.

everything looks great!

**Comment by allisonhorst** [comment]
fantastic thanks for all your help with this doc!
