### ISSUE TITLE
Create MEDS tech / software needs doc

### ISSUE THREAD

**Issue by allisonhorst** [UCSB-MEDS/UCSB-MEDS.github.io#6]
- [x] Meet w/ compute team
- [x] Decide on device needs 
- [ ] Get a list of software needs from teachers
- [x] Create doc & get feedback
- [x] Post

**Comment by jamiecmontgomery** [comment]
Doc is here: https://docs.google.com/document/d/1WYOGxeXA45yIr8dPNjdpT0BR_GHOV4PQuf7I6TxXK6I/edit

**Comment by allisonhorst** [comment]
writing up a separate installation guide for software, so closing this w/ minimum device requirements done.
